<?php

declare(strict_types=1);
/**
 * Generated by build/gen_test
 */
use LightnCandy\LightnCandy;
use PHPUnit\Framework\TestCase;

require_once(__DIR__ . '/test_util.php');

class CompilerTest extends TestCase
{
    /**
     * @covers LightnCandy\Compiler::getFuncName
     */
    public function testOn_getFuncName()
    {
        $method = new \ReflectionMethod('LightnCandy\Compiler', 'getFuncName');
        $method->setAccessible(true);
        $this->assertEquals('LR::test(', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['standalone' => 0, 'debug' => 0], 'runtime' => 'Runtime', 'runtimealias' => 'LR'], 'test', '',
        ])));
        $this->assertEquals('LL::test2(', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['standalone' => 0, 'debug' => 0], 'runtime' => 'Runtime', 'runtimealias' => 'LL'], 'test2', '',
        ])));
        $this->assertEquals('lala_abctest3(', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['standalone' => 1, 'debug' => 0], 'runtime' => 'Runtime', 'runtimealias' => 0, 'funcprefix' => 'lala_abc'], 'test3', '',
        ])));
        $this->assertEquals('RR::debug(\'abc\', \'test\', ', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['standalone' => 0, 'debug' => 1], 'runtime' => 'Runtime', 'runtimealias' => 'RR', 'funcprefix' => 'haha456'], 'test', 'abc',
        ])));
    }
    /**
     * @covers LightnCandy\Compiler::getVariableNames
     */
    public function testOn_getVariableNames()
    {
        $method = new \ReflectionMethod('LightnCandy\Compiler', 'getVariableNames');
        $method->setAccessible(true);
        $this->assertEquals(['array(array($in),array())', ['this']], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true]], [null],
        ])));
        $this->assertEquals(['array(array($in,$in),array())', ['this', 'this']], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true]], [null, null],
        ])));
        $this->assertEquals(['array(array(),array(\'a\'=>$in))', ['this']], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true]], ['a' => null],
        ])));
    }
    /**
     * @covers LightnCandy\Compiler::getVariableName
     */
    public function testOn_getVariableName()
    {
        $method = new \ReflectionMethod('LightnCandy\Compiler', 'getVariableName');
        $method->setAccessible(true);
        $this->assertEquals(['$in', 'this'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true,'debug' => 0]], [null],
        ])));
        $this->assertEquals(['(($inary && isset($in[\'true\'])) ? $in[\'true\'] : null)', '[true]'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true,'debug' => 0,'prop' => 0,'method' => 0,'mustlok' => 0,'mustlam' => 0,'lambda' => 0,'jslen' => 0]], ['true'],
        ])));
        $this->assertEquals(['(($inary && isset($in[\'false\'])) ? $in[\'false\'] : null)', '[false]'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true,'debug' => 0,'prop' => 0,'method' => 0,'mustlok' => 0,'mustlam' => 0,'lambda' => 0,'jslen' => 0]], ['false'],
        ])));
        $this->assertEquals(['true', 'true'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true,'debug' => 0]], [-1, 'true'],
        ])));
        $this->assertEquals(['false', 'false'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true,'debug' => 0]], [-1, 'false'],
        ])));
        $this->assertEquals(['(($inary && isset($in[\'2\'])) ? $in[\'2\'] : null)', '[2]'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true,'debug' => 0,'prop' => 0,'method' => 0,'mustlok' => 0,'mustlam' => 0,'lambda' => 0,'jslen' => 0]], ['2'],
        ])));
        $this->assertEquals(['2', '2'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true,'debug' => 0,'prop' => 0,'method' => 0]], [-1, '2'],
        ])));
        $this->assertEquals(['(($inary && isset($in[\'@index\'])) ? $in[\'@index\'] : null)', '[@index]'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => false,'debug' => 0,'prop' => 0,'method' => 0,'mustlok' => 0,'mustlam' => 0,'lambda' => 0,'jslen' => 0]], ['@index'],
        ])));
        $this->assertEquals(["(isset(\$cx['sp_vars']['index']) ? \$cx['sp_vars']['index'] : null)", '@[index]'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true,'debug' => 0,'prop' => 0,'method' => 0,'mustlok' => 0,'mustlam' => 0,'lambda' => 0,'jslen' => 0]], ['@index'],
        ])));
        $this->assertEquals(["(isset(\$cx['sp_vars']['key']) ? \$cx['sp_vars']['key'] : null)", '@[key]'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true,'debug' => 0,'prop' => 0,'method' => 0,'mustlok' => 0,'mustlam' => 0,'lambda' => 0,'jslen' => 0]], ['@key'],
        ])));
        $this->assertEquals(["(isset(\$cx['sp_vars']['first']) ? \$cx['sp_vars']['first'] : null)", '@[first]'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true,'debug' => 0,'prop' => 0,'method' => 0,'mustlok' => 0,'mustlam' => 0,'lambda' => 0,'jslen' => 0]], ['@first'],
        ])));
        $this->assertEquals(["(isset(\$cx['sp_vars']['last']) ? \$cx['sp_vars']['last'] : null)", '@[last]'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true,'debug' => 0,'prop' => 0,'method' => 0,'mustlok' => 0,'mustlam' => 0,'lambda' => 0,'jslen' => 0]], ['@last'],
        ])));
        $this->assertEquals(['(($inary && isset($in[\'"a"\'])) ? $in[\'"a"\'] : null)', '["a"]'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true,'debug' => 0,'prop' => 0,'method' => 0,'mustlok' => 0,'mustlam' => 0,'lambda' => 0,'jslen' => 0]], ['"a"'],
        ])));
        $this->assertEquals(['"a"', '"a"'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true,'debug' => 0]], [-1, '"a"'],
        ])));
        $this->assertEquals(['(($inary && isset($in[\'a\'])) ? $in[\'a\'] : null)', '[a]'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true,'debug' => 0,'prop' => 0,'method' => 0,'mustlok' => 0,'mustlam' => 0,'lambda' => 0,'jslen' => 0]], ['a'],
        ])));
        $this->assertEquals(['((isset($cx[\'scopes\'][count($cx[\'scopes\'])-1]) && is_array($cx[\'scopes\'][count($cx[\'scopes\'])-1]) && isset($cx[\'scopes\'][count($cx[\'scopes\'])-1][\'a\'])) ? $cx[\'scopes\'][count($cx[\'scopes\'])-1][\'a\'] : null)', '../[a]'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true,'debug' => 0,'prop' => 0,'method' => 0,'mustlok' => 0,'mustlam' => 0,'lambda' => 0,'jslen' => 0]], [1,'a'],
        ])));
        $this->assertEquals(['((isset($cx[\'scopes\'][count($cx[\'scopes\'])-3]) && is_array($cx[\'scopes\'][count($cx[\'scopes\'])-3]) && isset($cx[\'scopes\'][count($cx[\'scopes\'])-3][\'a\'])) ? $cx[\'scopes\'][count($cx[\'scopes\'])-3][\'a\'] : null)', '../../../[a]'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true,'debug' => 0,'prop' => 0,'method' => 0,'mustlok' => 0,'mustlam' => 0,'lambda' => 0,'jslen' => 0]], [3,'a'],
        ])));
        $this->assertEquals(['(($inary && isset($in[\'id\'])) ? $in[\'id\'] : null)', 'this.[id]'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => true,'debug' => 0,'prop' => 0,'method' => 0,'mustlok' => 0,'mustlam' => 0,'lambda' => 0,'jslen' => 0]], [null, 'id'],
        ])));
        $this->assertEquals(['LR::v($cx, $in, isset($in) ? $in : null, array(\'id\'))', 'this.[id]'], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['prop' => true,'spvar' => true,'debug' => 0,'method' => 0,'mustlok' => 0,'mustlam' => 0,'lambda' => 0,'jslen' => 0,'standalone' => 0], 'runtime' => 'Runtime', 'runtimealias' => 'LR'], [null, 'id'],
        ])));
    }
    /**
     * @covers LightnCandy\Compiler::addUsageCount
     */
    public function testOn_addUsageCount()
    {
        $method = new \ReflectionMethod('LightnCandy\Compiler', 'addUsageCount');
        $method->setAccessible(true);
        $this->assertEquals(1, $method->invokeArgs(null, array_by_ref([
            ['usedCount' => ['test' => []]], 'test', 'testname',
        ])));
        $this->assertEquals(3, $method->invokeArgs(null, array_by_ref([
            ['usedCount' => ['test' => ['testname' => 2]]], 'test', 'testname',
        ])));
        $this->assertEquals(5, $method->invokeArgs(null, array_by_ref([
            ['usedCount' => ['test' => ['testname' => 2]]], 'test', 'testname', 3,
        ])));
    }
}
