<?php

declare(strict_types=1);
/**
 * Generated by build/gen_test
 */
use LightnCandy\LightnCandy;
use PHPUnit\Framework\TestCase;

require_once(__DIR__ . '/test_util.php');

class ContextTest extends TestCase
{
    /**
     * @covers LightnCandy\Context::updateHelperTable
     */
    public function testOn_updateHelperTable()
    {
        $method = new \ReflectionMethod('LightnCandy\Context', 'updateHelperTable');
        $method->setAccessible(true);
        $this->assertEquals([], $method->invokeArgs(null, array_by_ref([
            [], [],
        ])));
        $this->assertEquals(['flags' => ['exhlp' => 1], 'helpers' => ['abc' => 1]], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['exhlp' => 1]], ['helpers' => ['abc']],
        ])));
        $this->assertEquals(['error' => ['You provide a custom helper named as \'abc\' in options[\'helpers\'], but the function abc() is not defined!'], 'flags' => ['exhlp' => 0]], $method->invokeArgs(null, array_by_ref([
            ['error' => [], 'flags' => ['exhlp' => 0]], ['helpers' => ['abc']],
        ])));
        $this->assertEquals(['flags' => ['exhlp' => 1], 'helpers' => ['\\LightnCandy\\Runtime::raw' => '\\LightnCandy\\Runtime::raw']], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['exhlp' => 1], 'helpers' => []], ['helpers' => ['\\LightnCandy\\Runtime::raw']],
        ])));
        $this->assertEquals(['flags' => ['exhlp' => 1], 'helpers' => ['test' => '\\LightnCandy\\Runtime::raw']], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['exhlp' => 1], 'helpers' => []], ['helpers' => ['test' => '\\LightnCandy\\Runtime::raw']],
        ])));
    }
}
