<?php

declare(strict_types=1);
/**
 * Generated by build/gen_test
 */
use LightnCandy\LightnCandy;
use PHPUnit\Framework\TestCase;

require_once(__DIR__ . '/test_util.php');

class ExporterTest extends TestCase
{
    /**
     * @covers LightnCandy\Exporter::closure
     */
    public function testOn_closure()
    {
        $method = new \ReflectionMethod('LightnCandy\Exporter', 'closure');
        $method->setAccessible(true);
        $this->assertEquals('function($a) {return;}', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['standalone' => 0]],  function ($a) {
                return;
            },
        ])));
        $this->assertEquals('function($a) {return;}', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['standalone' => 0]],   function ($a) {
                return;
            },
        ])));
    }
}
