<?php

declare(strict_types=1);
/**
 * Generated by build/gen_test
 */
use LightnCandy\LightnCandy;
use PHPUnit\Framework\TestCase;

require_once(__DIR__ . '/test_util.php');

class ExpressionTest extends TestCase
{
    /**
     * @covers LightnCandy\Expression::boolString
     */
    public function testOn_boolString()
    {
        $method = new \ReflectionMethod('LightnCandy\Expression', 'boolString');
        $this->assertEquals('true', $method->invokeArgs(null, array_by_ref([
            1,
        ])));
        $this->assertEquals('true', $method->invokeArgs(null, array_by_ref([
            999,
        ])));
        $this->assertEquals('false', $method->invokeArgs(null, array_by_ref([
            0,
        ])));
        $this->assertEquals('false', $method->invokeArgs(null, array_by_ref([
            -1,
        ])));
    }
    /**
     * @covers LightnCandy\Expression::listString
     */
    public function testOn_listString()
    {
        $method = new \ReflectionMethod('LightnCandy\Expression', 'listString');
        $this->assertEquals('', $method->invokeArgs(null, array_by_ref([
            [],
        ])));
        $this->assertEquals("'a'", $method->invokeArgs(null, array_by_ref([
            ['a'],
        ])));
        $this->assertEquals("'a','b','c'", $method->invokeArgs(null, array_by_ref([
            ['a', 'b', 'c'],
        ])));
    }
    /**
     * @covers LightnCandy\Expression::arrayString
     */
    public function testOn_arrayString()
    {
        $method = new \ReflectionMethod('LightnCandy\Expression', 'arrayString');
        $this->assertEquals('', $method->invokeArgs(null, array_by_ref([
            [],
        ])));
        $this->assertEquals("['a']", $method->invokeArgs(null, array_by_ref([
            ['a'],
        ])));
        $this->assertEquals("['a']['b']['c']", $method->invokeArgs(null, array_by_ref([
            ['a', 'b', 'c'],
        ])));
    }
    /**
     * @covers LightnCandy\Expression::analyze
     */
    public function testOn_analyze()
    {
        $method = new \ReflectionMethod('LightnCandy\Expression', 'analyze');
        $this->assertEquals([0, false, ['foo']], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0]], [0, 'foo'],
        ])));
        $this->assertEquals([1, false, ['foo']], $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0]], [1, 'foo'],
        ])));
    }
    /**
     * @covers LightnCandy\Expression::toString
     */
    public function testOn_toString()
    {
        $method = new \ReflectionMethod('LightnCandy\Expression', 'toString');
        $this->assertEquals('[a].[b]', $method->invokeArgs(null, array_by_ref([
            0, false, ['a', 'b'],
        ])));
        $this->assertEquals('@[root]', $method->invokeArgs(null, array_by_ref([
            0, true, ['root'],
        ])));
        $this->assertEquals('this', $method->invokeArgs(null, array_by_ref([
            0, false, null,
        ])));
        $this->assertEquals('this.[id]', $method->invokeArgs(null, array_by_ref([
            0, false, [null, 'id'],
        ])));
        $this->assertEquals('@[root].[a].[b]', $method->invokeArgs(null, array_by_ref([
            0, true, ['root', 'a', 'b'],
        ])));
        $this->assertEquals('../../[a].[b]', $method->invokeArgs(null, array_by_ref([
            2, false, ['a', 'b'],
        ])));
        $this->assertEquals('../[a\'b]', $method->invokeArgs(null, array_by_ref([
            1, false, ['a\'b'],
        ])));
    }
}
