<?php

declare(strict_types=1);
/**
 * Generated by build/gen_test
 */
use LightnCandy\LightnCandy;
use PHPUnit\Framework\TestCase;

require_once(__DIR__ . '/test_util.php');

class LightnCandyTest extends TestCase
{
    /**
     * @covers LightnCandy\LightnCandy::compilePartial
     */
    public function testOn_compilePartial()
    {
        $method = new \ReflectionMethod('LightnCandy\LightnCandy', 'compilePartial');
        $this->assertEquals(false, $method->invokeArgs(null, array_by_ref([
            '{{"}}', ['flags' => LightnCandy::FLAG_HANDLEBARS],
        ])));
    }
    /**
     * @covers LightnCandy\LightnCandy::handleError
     */
    public function testOn_handleError()
    {
        $method = new \ReflectionMethod('LightnCandy\LightnCandy', 'handleError');
        $method->setAccessible(true);
        $this->assertEquals(false, $method->invokeArgs(null, array_by_ref([
            ['error' => []],
        ])));
        $this->assertEquals(true, $method->invokeArgs(null, array_by_ref([
            ['error' => ['some error'], 'flags' => ['errorlog' => 0, 'exception' => 0]],
        ])));
    }
}
