<?php

declare(strict_types=1);
/**
 * Generated by build/gen_test
 */
use LightnCandy\LightnCandy;
use PHPUnit\Framework\TestCase;

require_once(__DIR__ . '/test_util.php');

class ParserTest extends TestCase
{
    /**
     * @covers LightnCandy\Parser::getExpression
     */
    public function testOn_getExpression()
    {
        $method = new \ReflectionMethod('LightnCandy\Parser', 'getExpression');
        $method->setAccessible(true);
        $this->assertEquals(['this'], $method->invokeArgs(null, array_by_ref([
            'this', ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 0]], 0,
        ])));
        $this->assertEquals([], $method->invokeArgs(null, array_by_ref([
            'this', ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 1]], 0,
        ])));
        $this->assertEquals([1], $method->invokeArgs(null, array_by_ref([
            '..', ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 1, 'parent' => 1], 'usedFeature' => ['parent' => 0]], 0,
        ])));
        $this->assertEquals([1], $method->invokeArgs(null, array_by_ref([
            '../', ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 1, 'parent' => 1], 'usedFeature' => ['parent' => 0]], 0,
        ])));
        $this->assertEquals([1], $method->invokeArgs(null, array_by_ref([
            '../.', ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 1, 'parent' => 1], 'usedFeature' => ['parent' => 0]], 0,
        ])));
        $this->assertEquals([1], $method->invokeArgs(null, array_by_ref([
            '../this', ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 1, 'parent' => 1], 'usedFeature' => ['parent' => 0]], 0,
        ])));
        $this->assertEquals([1, 'a'], $method->invokeArgs(null, array_by_ref([
            '../a', ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 1, 'parent' => 1], 'usedFeature' => ['parent' => 0]], 0,
        ])));
        $this->assertEquals([2, 'a', 'b'], $method->invokeArgs(null, array_by_ref([
            '../../a.b', ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 0, 'parent' => 1], 'usedFeature' => ['parent' => 0]], 0,
        ])));
        $this->assertEquals([2, '[a]', 'b'], $method->invokeArgs(null, array_by_ref([
            '../../[a].b', ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 0, 'parent' => 1], 'usedFeature' => ['parent' => 0]], 0,
        ])));
        $this->assertEquals([2, 'a', 'b'], $method->invokeArgs(null, array_by_ref([
            '../../[a].b', ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 0, 'parent' => 1], 'usedFeature' => ['parent' => 0]], 0,
        ])));
        $this->assertEquals([0, 'id'], $method->invokeArgs(null, array_by_ref([
            'this.id', ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'parent' => 1], 'usedFeature' => ['parent' => 0]], 0,
        ])));
        $this->assertEquals(['this', 'id'], $method->invokeArgs(null, array_by_ref([
            'this.id', ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 0, 'parent' => 1], 'usedFeature' => ['parent' => 0]], 0,
        ])));
        $this->assertEquals([0, 'id'], $method->invokeArgs(null, array_by_ref([
            './id', ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 0, 'parent' => 1], 'usedFeature' => ['parent' => 0]], 0,
        ])));
        $this->assertEquals([\LightnCandy\Parser::LITERAL, '\'a.b\''], $method->invokeArgs(null, array_by_ref([
            '"a.b"', ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 0, 'parent' => 1], 'usedFeature' => ['parent' => 0]], 1,
        ])));
        $this->assertEquals([\LightnCandy\Parser::LITERAL, '123'], $method->invokeArgs(null, array_by_ref([
            '123', ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 0, 'parent' => 1], 'usedFeature' => ['parent' => 0]], 1,
        ])));
        $this->assertEquals([\LightnCandy\Parser::LITERAL, 'null'], $method->invokeArgs(null, array_by_ref([
            'null', ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 0, 'parent' => 1], 'usedFeature' => ['parent' => 0]], 1,
        ])));
    }
    /**
     * @covers LightnCandy\Parser::parse
     */
    public function testOn_parse()
    {
        $method = new \ReflectionMethod('LightnCandy\Parser', 'parse');
        $this->assertEquals([false, [[]]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,''], ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 1, 'namev' => 0, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([true, [[]]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,'{{',0,'{',0,''], ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 1, 'namev' => 0, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([true, [[]]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,''], ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 1, 'namev' => 0, 'noesc' => 1], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['a']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'a'], ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 1, 'namev' => 0, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['a'], ['b']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'a  b'], ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 1, 'namev' => 0, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['a'], ['"b'], ['c"']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'a "b c"'], ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 1, 'namev' => 0, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['a'], [-1, '\'b c\'']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'a "b c"'], ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'namev' => 0, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['a'], ['[b'], ['c]']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'a [b c]'], ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 1, 'namev' => 0, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['a'], ['[b'], ['c]']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'a [b c]'], ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 1, 'namev' => 1, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['a'], ['b c']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'a [b c]'], ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'namev' => 0, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['a'], ['b c']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'a [b c]'], ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['a'], 'q' => ['b c']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'a q=[b c]'], ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['a'], ['q=[b c']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'a [q=[b c]'], ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['a'], 'q' => ['[b'], ['c]']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'a q=[b c]'], ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 1, 'namev' => 1, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['a'], 'q' => ['b'], ['c']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'a [q]=b c'], ['flags' => ['strpar' => 0, 'advar' => 0, 'this' => 1, 'namev' => 1, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['a'], 'q' => [-1, '\'b c\'']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'a q="b c"'], ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [[-2, [['foo'], ['bar']], '(foo bar)']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'(foo bar)'], ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0, 'exhlp' => 1, 'lambda' => 0], 'ops' => ['seperator' => ''], 'usedFeature' => ['subexp' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['foo'], ["'=='"], ['bar']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,"foo '==' bar"], ['flags' => ['strpar' => 0, 'advar' => 1, 'namev' => 1, 'noesc' => 0, 'this' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [[-2, [['foo'], ['bar']], '( foo bar)']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'( foo bar)'], ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0, 'exhlp' => 1, 'lambda' => 0], 'ops' => ['seperator' => ''], 'usedFeature' => ['subexp' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['a'], [-1, '\' b c\'']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'a " b c"'], ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'namev' => 0, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['a'], 'q' => [-1, '\' b c\'']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'a q=" b c"'], ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['foo'], [-1, "' =='"], ['bar']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,"foo \' ==\' bar"], ['flags' => ['strpar' => 0, 'advar' => 1, 'namev' => 1, 'noesc' => 0, 'this' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['a'], [' b c']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'a [ b c]'], ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['a'], 'q' => [-1, "' d e'"]]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,"a q=\' d e\'"], ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, ['q' => [-2, [['foo'], ['bar']], '( foo bar)']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,0,'q=( foo bar)'], ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0, 'exhlp' => 0, 'lambda' => 0], 'usedFeature' => ['subexp' => 0], 'ops' => ['seperator' => 0], 'rawblock' => false, 'helperresolver' => 0],
        ])));
        $this->assertEquals([false, [['foo']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,'>','foo'], ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0, 'exhlp' => 0, 'lambda' => 0], 'usedFeature' => ['subexp' => 0], 'ops' => ['seperator' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['foo']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,'>','"foo"'], ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0, 'exhlp' => 0, 'lambda' => 0], 'usedFeature' => ['subexp' => 0], 'ops' => ['seperator' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['foo']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,'>','[foo] '], ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0, 'exhlp' => 0, 'lambda' => 0], 'usedFeature' => ['subexp' => 0], 'ops' => ['seperator' => 0], 'rawblock' => false],
        ])));
        $this->assertEquals([false, [['foo']]], $method->invokeArgs(null, array_by_ref([
            [0,0,0,0,0,0,'>','\\\'foo\\\''], ['flags' => ['strpar' => 0, 'advar' => 1, 'this' => 1, 'namev' => 1, 'noesc' => 0, 'exhlp' => 0, 'lambda' => 0], 'usedFeature' => ['subexp' => 0], 'ops' => ['seperator' => 0], 'rawblock' => false],
        ])));
    }
    /**
     * @covers LightnCandy\Parser::getPartialName
     */
    public function testOn_getPartialName()
    {
        $method = new \ReflectionMethod('LightnCandy\Parser', 'getPartialName');
        $this->assertEquals(null, $method->invokeArgs(null, array_by_ref([
            [],
        ])));
        $this->assertEquals(['foo'], $method->invokeArgs(null, array_by_ref([
            ['foo'],
        ])));
        $this->assertEquals(['foo'], $method->invokeArgs(null, array_by_ref([
            ['"foo"'],
        ])));
        $this->assertEquals(['foo'], $method->invokeArgs(null, array_by_ref([
            ['[foo]'],
        ])));
        $this->assertEquals(['foo'], $method->invokeArgs(null, array_by_ref([
            ["\\'foo\\'"],
        ])));
        $this->assertEquals(['foo'], $method->invokeArgs(null, array_by_ref([
            [0, 'foo'], 1,
        ])));
    }
    /**
     * @covers LightnCandy\Parser::subexpression
     */
    public function testOn_subexpression()
    {
        $method = new \ReflectionMethod('LightnCandy\Parser', 'subexpression');
        $this->assertEquals([\LightnCandy\Parser::SUBEXP, [['a'], ['b']], '(a b)'], $method->invokeArgs(null, array_by_ref([
            '(a b)', ['usedFeature' => ['subexp' => 0], 'flags' => ['advar' => 0, 'namev' => 0, 'this' => 0, 'exhlp' => 1, 'strpar' => 0]],
        ])));
    }
    /**
     * @covers LightnCandy\Parser::isSubExp
     */
    public function testOn_isSubExp()
    {
        $method = new \ReflectionMethod('LightnCandy\Parser', 'isSubExp');
        $this->assertEquals(false, $method->invokeArgs(null, array_by_ref([
            0,
        ])));
        $this->assertEquals(false, $method->invokeArgs(null, array_by_ref([
            [],
        ])));
        $this->assertEquals(false, $method->invokeArgs(null, array_by_ref([
            [\LightnCandy\Parser::SUBEXP, 0],
        ])));
        $this->assertEquals(false, $method->invokeArgs(null, array_by_ref([
            [\LightnCandy\Parser::SUBEXP, 0, 0],
        ])));
        $this->assertEquals(false, $method->invokeArgs(null, array_by_ref([
            [\LightnCandy\Parser::SUBEXP, 0, '', 0],
        ])));
        $this->assertEquals(true, $method->invokeArgs(null, array_by_ref([
            [\LightnCandy\Parser::SUBEXP, 0, ''],
        ])));
    }
    /**
     * @covers LightnCandy\Parser::advancedVariable
     */
    public function testOn_advancedVariable()
    {
        $method = new \ReflectionMethod('LightnCandy\Parser', 'advancedVariable');
        $method->setAccessible(true);
        $this->assertEquals([['this']], $method->invokeArgs(null, array_by_ref([
            ['this'], ['flags' => ['advar' => 1, 'namev' => 1, 'this' => 0,]], 0,
        ])));
        $this->assertEquals([[]], $method->invokeArgs(null, array_by_ref([
            ['this'], ['flags' => ['advar' => 1, 'namev' => 1, 'this' => 1]], 0,
        ])));
        $this->assertEquals([['a']], $method->invokeArgs(null, array_by_ref([
            ['a'], ['flags' => ['advar' => 1, 'namev' => 1, 'this' => 0, 'strpar' => 0]], 0,
        ])));
        $this->assertEquals([['a'], ['b']], $method->invokeArgs(null, array_by_ref([
            ['a', 'b'], ['flags' => ['advar' => 1, 'namev' => 1, 'this' => 0, 'strpar' => 0]], 0,
        ])));
        $this->assertEquals(['a' => ['b']], $method->invokeArgs(null, array_by_ref([
            ['a=b'], ['flags' => ['advar' => 1, 'namev' => 1, 'this' => 0, 'strpar' => 0]], 0,
        ])));
        $this->assertEquals(['fo o' => [\LightnCandy\Parser::LITERAL, '123']], $method->invokeArgs(null, array_by_ref([
            ['[fo o]=123'], ['flags' => ['advar' => 1, 'namev' => 1, 'this' => 0]], 0,
        ])));
        $this->assertEquals(['fo o' => [\LightnCandy\Parser::LITERAL, '\'bar\'']], $method->invokeArgs(null, array_by_ref([
            ['[fo o]="bar"'], ['flags' => ['advar' => 1, 'namev' => 1, 'this' => 0]], 0,
        ])));
    }
    /**
     * @covers LightnCandy\Parser::analyze
     */
    public function testOn_analyze()
    {
        $method = new \ReflectionMethod('LightnCandy\Parser', 'analyze');
        $method->setAccessible(true);
        $this->assertEquals(['foo', 'bar'], $method->invokeArgs(null, array_by_ref([
            'foo bar', ['flags' => ['advar' => 1]],
        ])));
        $this->assertEquals(['foo', "'bar'"], $method->invokeArgs(null, array_by_ref([
            "foo 'bar'", ['flags' => ['advar' => 1]],
        ])));
        $this->assertEquals(['[fo o]', '"bar"'], $method->invokeArgs(null, array_by_ref([
            '[fo o] "bar"', ['flags' => ['advar' => 1]],
        ])));
        $this->assertEquals(['fo=123', 'bar="45', '6"'], $method->invokeArgs(null, array_by_ref([
            'fo=123 bar="45 6"', ['flags' => ['advar' => 0]],
        ])));
        $this->assertEquals(['fo=123', 'bar="45 6"'], $method->invokeArgs(null, array_by_ref([
            'fo=123 bar="45 6"', ['flags' => ['advar' => 1]],
        ])));
        $this->assertEquals(['[fo', 'o]=123'], $method->invokeArgs(null, array_by_ref([
            '[fo o]=123', ['flags' => ['advar' => 0]],
        ])));
        $this->assertEquals(['[fo o]=123'], $method->invokeArgs(null, array_by_ref([
            '[fo o]=123', ['flags' => ['advar' => 1]],
        ])));
        $this->assertEquals(['[fo o]=123', 'bar="456"'], $method->invokeArgs(null, array_by_ref([
            '[fo o]=123 bar="456"', ['flags' => ['advar' => 1]],
        ])));
        $this->assertEquals(['[fo o]="1 2 3"'], $method->invokeArgs(null, array_by_ref([
            '[fo o]="1 2 3"', ['flags' => ['advar' => 1]],
        ])));
        $this->assertEquals(['foo', 'a=(foo a=(foo a="ok"))'], $method->invokeArgs(null, array_by_ref([
            'foo a=(foo a=(foo a="ok"))', ['flags' => ['advar' => 1]],
        ])));
    }
}
