<?php

declare(strict_types=1);
/**
 * Generated by build/gen_test
 */
use LightnCandy\LightnCandy;
use LightnCandy\Runtime;
use PHPUnit\Framework\TestCase;

require_once(__DIR__ . '/test_util.php');

class RuntimeTest extends TestCase
{
    /**
     * @covers LightnCandy\Runtime::debug
     */
    public function testOn_debug()
    {
        $method = new \ReflectionMethod('LightnCandy\Runtime', 'debug');
        $this->assertEquals('{{123}}', $method->invokeArgs(null, array_by_ref([
            '123', 'miss', ['flags' => ['debug' => Runtime::DEBUG_TAGS], 'runtime' => 'LightnCandy\\Runtime'], '',
        ])));
        $this->assertEquals('<!--MISSED((-->{{#123}}<!--))--><!--SKIPPED--><!--MISSED((-->{{/123}}<!--))-->', $method->invokeArgs(null, array_by_ref([
            '123', 'wi', ['flags' => ['debug' => Runtime::DEBUG_TAGS_HTML], 'runtime' => 'LightnCandy\\Runtime'], false, null, false, function () {
                return 'A';
            },
        ])));
    }
    /**
     * @covers LightnCandy\Runtime::v
     */
    public function testOn_v()
    {
        $method = new \ReflectionMethod('LightnCandy\Runtime', 'v');
        $this->assertEquals(null, $method->invokeArgs(null, array_by_ref([
            ['scopes' => [], 'flags' => ['prop' => 0, 'method' => 0, 'mustlok' => 0]], null, 0, ['a', 'b'],
        ])));
        $this->assertEquals(3, $method->invokeArgs(null, array_by_ref([
            ['scopes' => [], 'flags' => ['prop' => 0, 'method' => 0], 'mustlok' => 0], null, ['a' => ['b' => 3]], ['a', 'b'],
        ])));
        $this->assertEquals(null, $method->invokeArgs(null, array_by_ref([
            ['scopes' => [], 'flags' => ['prop' => 0, 'method' => 0, 'mustlok' => 0]], null, (object) ['a' => ['b' => 3]], ['a', 'b'],
        ])));
        $this->assertEquals(3, $method->invokeArgs(null, array_by_ref([
            ['scopes' => [], 'flags' => ['prop' => 1, 'method' => 0, 'mustlok' => 0]], null, (object) ['a' => ['b' => 3]], ['a', 'b'],
        ])));
    }
    /**
     * @covers LightnCandy\Runtime::ifvar
     */
    public function testOn_ifvar()
    {
        $method = new \ReflectionMethod('LightnCandy\Runtime', 'ifvar');
        $this->assertEquals(false, $method->invokeArgs(null, array_by_ref([
            [], null, false,
        ])));
        $this->assertEquals(false, $method->invokeArgs(null, array_by_ref([
            [], 0, false,
        ])));
        $this->assertEquals(true, $method->invokeArgs(null, array_by_ref([
            [], 0, true,
        ])));
        $this->assertEquals(false, $method->invokeArgs(null, array_by_ref([
            [], false, false,
        ])));
        $this->assertEquals(true, $method->invokeArgs(null, array_by_ref([
            [], true, false,
        ])));
        $this->assertEquals(true, $method->invokeArgs(null, array_by_ref([
            [], 1, false,
        ])));
        $this->assertEquals(false, $method->invokeArgs(null, array_by_ref([
            [], '', false,
        ])));
        $this->assertEquals(false, $method->invokeArgs(null, array_by_ref([
            [], [], false,
        ])));
        $this->assertEquals(true, $method->invokeArgs(null, array_by_ref([
            [], [''], false,
        ])));
        $this->assertEquals(true, $method->invokeArgs(null, array_by_ref([
            [], [0], false,
        ])));
    }
    /**
     * @covers LightnCandy\Runtime::isec
     */
    public function testOn_isec()
    {
        $method = new \ReflectionMethod('LightnCandy\Runtime', 'isec');
        $this->assertEquals(true, $method->invokeArgs(null, array_by_ref([
            [], null,
        ])));
        $this->assertEquals(false, $method->invokeArgs(null, array_by_ref([
            [], 0,
        ])));
        $this->assertEquals(true, $method->invokeArgs(null, array_by_ref([
            [], false,
        ])));
        $this->assertEquals(false, $method->invokeArgs(null, array_by_ref([
            [], 'false',
        ])));
        $this->assertEquals(true, $method->invokeArgs(null, array_by_ref([
            [], [],
        ])));
        $this->assertEquals(false, $method->invokeArgs(null, array_by_ref([
            [], ['1'],
        ])));
    }
    /**
     * @covers LightnCandy\Runtime::enc
     */
    public function testOn_enc()
    {
        $method = new \ReflectionMethod('LightnCandy\Runtime', 'enc');
        $this->assertEquals('a', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['mustlam' => 0, 'lambda' => 0]], 'a',
        ])));
        $this->assertEquals('a&amp;b', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['mustlam' => 0, 'lambda' => 0]], 'a&b',
        ])));
        $this->assertEquals('a&#039;b', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['mustlam' => 0, 'lambda' => 0]], 'a\'b',
        ])));
        $this->assertEquals('a&b', $method->invokeArgs(null, array_by_ref([
            null, new \LightnCandy\SafeString('a&b'),
        ])));
    }
    /**
     * @covers LightnCandy\Runtime::encq
     */
    public function testOn_encq()
    {
        $method = new \ReflectionMethod('LightnCandy\Runtime', 'encq');
        $this->assertEquals('a', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['mustlam' => 0, 'lambda' => 0]], 'a',
        ])));
        $this->assertEquals('a&amp;b', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['mustlam' => 0, 'lambda' => 0]], 'a&b',
        ])));
        $this->assertEquals('a&#x27;b', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['mustlam' => 0, 'lambda' => 0]], 'a\'b',
        ])));
        $this->assertEquals('&#x60;a&#x27;b', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['mustlam' => 0, 'lambda' => 0]], '`a\'b',
        ])));
    }
    /**
     * @covers LightnCandy\Runtime::sec
     */
    public function testOn_sec()
    {
        $method = new \ReflectionMethod('LightnCandy\Runtime', 'sec');
        $this->assertEquals('', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'mustsec' => 0, 'lambda' => 0]], false, null, false, false, function () {
                return 'A';
            },
        ])));
        $this->assertEquals('', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'mustsec' => 0, 'lambda' => 0]], null, null, null, false, function () {
                return 'A';
            },
        ])));
        $this->assertEquals('A', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'mustsec' => 0, 'lambda' => 0]], true, null, true, false, function () {
                return 'A';
            },
        ])));
        $this->assertEquals('A', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'mustsec' => 0, 'lambda' => 0]], 0, null, 0, false, function () {
                return 'A';
            },
        ])));
        $this->assertEquals('-a=', $method->invokeArgs(null, array_by_ref([
            ['scopes' => [], 'flags' => ['spvar' => 0, 'mustlam' => 0, 'lambda' => 0]], ['a'], null, ['a'], false, function ($c, $i) {
                return "-$i=";
            },
        ])));
        $this->assertEquals('-a=-b=', $method->invokeArgs(null, array_by_ref([
            ['scopes' => [], 'flags' => ['spvar' => 0, 'mustlam' => 0, 'lambda' => 0]], ['a','b'], null, ['a','b'], false, function ($c, $i) {
                return "-$i=";
            },
        ])));
        $this->assertEquals('', $method->invokeArgs(null, array_by_ref([
            ['scopes' => [], 'flags' => ['spvar' => 0, 'mustlam' => 0, 'lambda' => 0]], 'abc', null, 'abc', true, function ($c, $i) {
                return "-$i=";
            },
        ])));
        $this->assertEquals('-b=', $method->invokeArgs(null, array_by_ref([
            ['scopes' => [], 'flags' => ['spvar' => 0, 'mustlam' => 0, 'lambda' => 0]], ['a' => 'b'], null, ['a' => 'b'], true, function ($c, $i) {
                return "-$i=";
            },
        ])));
        $this->assertEquals('b', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'mustsec' => 0, 'lambda' => 0]], 'b', null, 'b', false, function ($c, $i) {
                return print_r($i, true);
            },
        ])));
        $this->assertEquals('1', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'mustsec' => 0, 'lambda' => 0]], 1, null, 1, false, function ($c, $i) {
                return print_r($i, true);
            },
        ])));
        $this->assertEquals('0', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'mustsec' => 0, 'lambda' => 0]], 0, null, 0, false, function ($c, $i) {
                return print_r($i, true);
            },
        ])));
        $this->assertEquals('{"b":"c"}', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'lambda' => 0]], ['b' => 'c'], null, ['b' => 'c'], false, function ($c, $i) {
                return json_encode($i);
            },
        ])));
        $this->assertEquals('inv', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'lambda' => 0]], [], null, 0, true, function ($c, $i) {
                return 'cb';
            }, function ($c, $i) {
                return 'inv';
            },
        ])));
        $this->assertEquals('inv', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'lambda' => 0]], [], null, 0, false, function ($c, $i) {
                return 'cb';
            }, function ($c, $i) {
                return 'inv';
            },
        ])));
        $this->assertEquals('inv', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'lambda' => 0]], false, null, 0, true, function ($c, $i) {
                return 'cb';
            }, function ($c, $i) {
                return 'inv';
            },
        ])));
        $this->assertEquals('inv', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'mustsec' => 0, 'lambda' => 0]], false, null, 0, false, function ($c, $i) {
                return 'cb';
            }, function ($c, $i) {
                return 'inv';
            },
        ])));
        $this->assertEquals('inv', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'lambda' => 0]], '', null, 0, true, function ($c, $i) {
                return 'cb';
            }, function ($c, $i) {
                return 'inv';
            },
        ])));
        $this->assertEquals('cb', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'mustsec' => 0, 'lambda' => 0]], '', null, 0, false, function ($c, $i) {
                return 'cb';
            }, function ($c, $i) {
                return 'inv';
            },
        ])));
        $this->assertEquals('inv', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'lambda' => 0]], 0, null, 0, true, function ($c, $i) {
                return 'cb';
            }, function ($c, $i) {
                return 'inv';
            },
        ])));
        $this->assertEquals('cb', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'mustsec' => 0, 'lambda' => 0]], 0, null, 0, false, function ($c, $i) {
                return 'cb';
            }, function ($c, $i) {
                return 'inv';
            },
        ])));
        $this->assertEquals('inv', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'lambda' => 0]], new stdClass(), null, 0, true, function ($c, $i) {
                return 'cb';
            }, function ($c, $i) {
                return 'inv';
            },
        ])));
        $this->assertEquals('cb', $method->invokeArgs(null, array_by_ref([
            ['flags' => ['spvar' => 0, 'mustlam' => 0, 'mustsec' => 0, 'lambda' => 0]], new stdClass(), null, 0, false, function ($c, $i) {
                return 'cb';
            }, function ($c, $i) {
                return 'inv';
            },
        ])));
        $this->assertEquals('268', $method->invokeArgs(null, array_by_ref([
            ['scopes' => [], 'flags' => ['spvar' => 1, 'mustlam' => 0, 'lambda' => 0], 'sp_vars' => ['root' => 0]], [1,3,4], null, 0, false, function ($c, $i) {
                return $i * 2;
            },
        ])));
        $this->assertEquals('038', $method->invokeArgs(null, array_by_ref([
            ['scopes' => [], 'flags' => ['spvar' => 1, 'mustlam' => 0, 'lambda' => 0], 'sp_vars' => ['root' => 0]], [1,3,'a' => 4], null, 0, true, function ($c, $i) {
                return $i * $c['sp_vars']['index'];
            },
        ])));
    }
    /**
     * @covers LightnCandy\Runtime::wi
     */
    public function testOn_wi()
    {
        $method = new \ReflectionMethod('LightnCandy\Runtime', 'wi');
        $this->assertEquals('', $method->invokeArgs(null, array_by_ref([
            [], false, null, false, function () {
                return 'A';
            },
        ])));
        $this->assertEquals('', $method->invokeArgs(null, array_by_ref([
            [], null, null, null, function () {
                return 'A';
            },
        ])));
        $this->assertEquals('{"a":"b"}', $method->invokeArgs(null, array_by_ref([
            [], ['a' => 'b'], null, ['a' => 'c'], function ($c, $i) {
                return json_encode($i);
            },
        ])));
        $this->assertEquals('-b=', $method->invokeArgs(null, array_by_ref([
            [], 'b', null, ['a' => 'b'], function ($c, $i) {
                return "-$i=";
            },
        ])));
    }
}
