<?php

declare(strict_types=1);
/**
 * Generated by build/gen_test
 */
use LightnCandy\LightnCandy;
use PHPUnit\Framework\TestCase;

require_once(__DIR__ . '/test_util.php');

class ValidatorTest extends TestCase
{
    /**
     * @covers LightnCandy\Validator::delimiter
     */
    public function testOn_delimiter()
    {
        $method = new \ReflectionMethod('LightnCandy\Validator', 'delimiter');
        $method->setAccessible(true);
        $this->assertEquals(null, $method->invokeArgs(null, array_by_ref([
            array_fill(0, 11, ''), [],
        ])));
        $this->assertEquals(null, $method->invokeArgs(null, array_by_ref([
            [0, 0, 0, 0, 0, '{{', '#', '...', '}}'], [],
        ])));
        $this->assertEquals(true, $method->invokeArgs(null, array_by_ref([
            [0, 0, 0, 0, 0, '{', '#', '...', '}'], [],
        ])));
    }
    /**
     * @covers LightnCandy\Validator::operator
     */
    public function testOn_operator()
    {
        $method = new \ReflectionMethod('LightnCandy\Validator', 'operator');
        $method->setAccessible(true);
        $this->assertEquals(null, $method->invokeArgs(null, array_by_ref([
            '', [], [],
        ])));
        $this->assertEquals(2, $method->invokeArgs(null, array_by_ref([
            '^', ['usedFeature' => ['isec' => 1], 'level' => 0, 'currentToken' => [0,0,0,0,0,0,0,0], 'elselvl' => [], 'flags' => ['spvar' => 0], 'elsechain' => false, 'helperresolver' => 0], [['foo']],
        ])));
        $this->assertEquals(true, $method->invokeArgs(null, array_by_ref([
            '/', ['stack' => ['[with]', '#'], 'level' => 1, 'currentToken' => [0,0,0,0,0,0,0,'with'], 'flags' => ['nohbh' => 0]], [[]],
        ])));
        $this->assertEquals(4, $method->invokeArgs(null, array_by_ref([
            '#', ['usedFeature' => ['sec' => 3], 'level' => 0, 'currentToken' => [0,0,0,0,0,0,0,0], 'flags' => ['spvar' => 0], 'elsechain' => false, 'elselvl' => [], 'helperresolver' => 0], [['x']],
        ])));
        $this->assertEquals(5, $method->invokeArgs(null, array_by_ref([
            '#', ['usedFeature' => ['if' => 4], 'level' => 0, 'currentToken' => [0,0,0,0,0,0,0,0], 'flags' => ['spvar' => 0, 'nohbh' => 0], 'elsechain' => false, 'elselvl' => [], 'helperresolver' => 0], [['if']],
        ])));
        $this->assertEquals(6, $method->invokeArgs(null, array_by_ref([
            '#', ['usedFeature' => ['with' => 5], 'level' => 0, 'flags' => ['nohbh' => 0, 'runpart' => 0, 'spvar' => 0], 'currentToken' => [0,0,0,0,0,0,0,0], 'elsechain' => false, 'elselvl' => [], 'helperresolver' => 0], [['with']],
        ])));
        $this->assertEquals(7, $method->invokeArgs(null, array_by_ref([
            '#', ['usedFeature' => ['each' => 6], 'level' => 0, 'currentToken' => [0,0,0,0,0,0,0,0], 'flags' => ['spvar' => 0, 'nohbh' => 0], 'elsechain' => false, 'elselvl' => [], 'helperresolver' => 0], [['each']],
        ])));
        $this->assertEquals(8, $method->invokeArgs(null, array_by_ref([
            '#', ['usedFeature' => ['unless' => 7], 'level' => 0, 'currentToken' => [0,0,0,0,0,0,0,0], 'flags' => ['spvar' => 0, 'nohbh' => 0], 'elsechain' => false, 'elselvl' => [], 'helperresolver' => 0], [['unless']],
        ])));
        $this->assertEquals(9, $method->invokeArgs(null, array_by_ref([
            '#', ['helpers' => ['abc' => ''], 'usedFeature' => ['helper' => 8], 'level' => 0, 'currentToken' => [0,0,0,0,0,0,0,0], 'flags' => ['spvar' => 0], 'elsechain' => false, 'elselvl' => []], [['abc']],
        ])));
        $this->assertEquals(11, $method->invokeArgs(null, array_by_ref([
            '#', ['helpers' => ['abc' => ''], 'usedFeature' => ['helper' => 10], 'level' => 0, 'currentToken' => [0,0,0,0,0,0,0,0], 'flags' => ['spvar' => 0], 'elsechain' => false, 'elselvl' => []], [['abc']],
        ])));
        $this->assertEquals(true, $method->invokeArgs(null, array_by_ref([
            '>', ['partialresolver' => false, 'usedFeature' => ['partial' => 7], 'level' => 0, 'flags' => ['skippartial' => 0, 'runpart' => 0, 'spvar' => 0], 'currentToken' => [0,0,0,0,0,0,0,0], 'elsechain' => false, 'elselvl' => []], ['test'],
        ])));
    }
}
